package com.cratechnologie.budget.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FinancialYearAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialYearAllPropertiesEquals(FinancialYear expected, FinancialYear actual) {
        assertFinancialYearAutoGeneratedPropertiesEquals(expected, actual);
        assertFinancialYearAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialYearAllUpdatablePropertiesEquals(FinancialYear expected, FinancialYear actual) {
        assertFinancialYearUpdatableFieldsEquals(expected, actual);
        assertFinancialYearUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialYearAutoGeneratedPropertiesEquals(FinancialYear expected, FinancialYear actual) {
        assertThat(actual)
            .as("Verify FinancialYear auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialYearUpdatableFieldsEquals(FinancialYear expected, FinancialYear actual) {
        assertThat(actual)
            .as("Verify FinancialYear relevant properties")
            .satisfies(a -> assertThat(a.getTheYear()).as("check theYear").isEqualTo(expected.getTheYear()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialYearUpdatableRelationshipsEquals(FinancialYear expected, FinancialYear actual) {
        // empty method
    }
}
